### ISSUE TITLE
SEC_ERROR_TOKEN_NOT_LOGGED_IN

### ISSUE THREAD

**Issue by kram12085** [jdjaxon/linux_cac#9]
Linux Mint 20.2 and Firefox 99.0.1

Since I got my CAC working thanks to this script, it will always work for about 5 minutes then I get this error. I have to remove and reinsert the CAC and restart Firefox to resolve. Searching online it appears to be long-time issue with FF but I couldn't find any fix for it. Any idea how it can be resolved? Thank you.
![Screenshot from 2022-09-23 10-43-07](https://user-images.githubusercontent.com/1285519/192027083-ee47ff32-62b2-46db-89af-7acfefd1848d.png)

**Comment by jdjaxon** [comment]
I don't currently know of a way to fix this. I'll have to do some research and testing. The 5 minute "timeout" is new to me. I should also note that i have only tested this script on Ubuntu and PopOS, which is why i claim to only support those two in the readme. That being said, the script should work on any debian-based distro really.

Worst-case scenario is that this is a browser issue. To test this, you could try using any other browser. Other browsers with success cases using this script are chrome and brave, which i believe both use the nssdb. This means you'll have to install that browser, start it to initialize the DB, and rerun the script to load the certs into that new DB. If you decide to try this and keep having issues, let me know, and we can try to find another solution.

As a side note, was your firefox installed using apt?

**Comment by kram12085** [comment]
Based on the Firefox bug reports from years ago I found online, I'm almost sure this is a FF issue but I can't find any resolution. Chrome never worked right for an unknown reason, it would loop and continually ask for the pin despite me running the script on a clean install of Chrome.

I can't recall but I'm pretty sure it was an apt installation since I don't use snap or the other methods. FF does have a [special arrangement with Mint](https://news.itsfoss.com/linux-mint-mozilla-firefox/) though, so it may be a modified version. 

I appreciate you looking into this even though I'm almost sure it's a FF issue and not with your script!

**Comment by jdjaxon** [comment]
Of course!

If you had never started chrome before running the script, you would not have initialized the database. Now that you've ran chrome and created the DB, run the script again to load the DB, and chrome should work. Let me know if this doesn't work for chrome. I'm happy to help troubleshoot.

**Comment by kram12085** [comment]
> If you had never started chrome before running the script, you would not have initialized the database. Now that you've ran chrome and created the DB, run the script again to load the DB, and chrome should work. Let me know if this doesn't work for chrome. I'm happy to help troubleshoot.

Yup, tried that and it still loops. I mentioned it in my previous [report](https://github.com/jdjaxon/linux_cac/issues/4) but since I got FF to work, I quit trying with Chrome. It's odd since I rarely use Chrome so it shouldn't have a lot of baggage or modifications.

**Comment by jdjaxon** [comment]
For both Ubuntu and PopOS 20.04 LTS (basically the same distro) with no other middleware previously installed, I can consistently have both browsers function with the following steps:
1. Download firefox and chrome, if not already installed
2. Start and close both browsers to initialize their respective DBs
3. Run script (should not have the browsers open during this install)
4. Run `systemctl enable pcscd` (a step that I've fixed on a separate branch)

This has worked for all of the people that work in my shop and have used this script. This is on both fresh installs and older, working installs. I have seen multiple people have issues if they've ever installed any middleware other than cackey - even if it has since been removed. Not sure what causes this. My theory is that some artifacts left from the other middleware somehow conflict with cackey,  but i honestly don't know.

**Comment by kram12085** [comment]
Here's what I did just now:

1. Close both browsers
2. Uninstall Chrome via Synaptic Package Manager
3. Reinstall via Synaptic
4. Open Chrome
5. Close Chrome
6. Run automatic script
7. Run `systemctl enable pcscd`

Same issue, it will ask for my pin twice in a row, spin for about a minute, repeat. I'm going to close this report since it's likely something funky on my end. And now that my email migrated to NIPR-only, it's unfortunately not as useful (and haven't been able to get rasxtra.usar.army.mil to work in Linux since ~2017). Thank you for your time and effort!
